ARG SOURCE_IMAGE="ucore"
ARG SOURCE_SUFFIX="minimal"
ARG SOURCE_TAG="stable"

### 2. SOURCE IMAGE
FROM ghcr.io/ublue-os/${SOURCE_IMAGE}-${SOURCE_SUFFIX}:${SOURCE_TAG}

### 3. MODIFICATIONS
COPY /server /ctx

RUN mkdir -p /var/lib/alternatives && \
    /ctx/build/build-all.sh && \
    dnf5 clean all
