ARG SOURCE_IMAGE="bazzite"
ARG SOURCE_SUFFIX="nvidia-open"
ARG SOURCE_TAG="stable"

### 2. SOURCE IMAGE
FROM ghcr.io/ublue-os/${SOURCE_IMAGE}-${SOURCE_SUFFIX}:${SOURCE_TAG}

### 3. MODIFICATIONS
COPY /gamerrig /ctx

RUN mkdir -p /var/lib/alternatives && \
    /ctx/build/build-all.sh
