ARG SOURCE_IMAGE="kinoite"
ARG SOURCE_SUFFIX="main"
ARG SOURCE_TAG="44"

### 2. SOURCE IMAGE
FROM ghcr.io/ublue-os/${SOURCE_IMAGE}-${SOURCE_SUFFIX}:${SOURCE_TAG}

### 3. MODIFICATIONS
COPY /desktop /ctx

RUN mkdir -p /var/lib/alternatives && \
    /ctx/build/build-all.sh && \
    dnf5 clean all
